version: '3.5'

networks:
  backend:
    driver: ${NETWORK_DRIVER}
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: queue
    hostname: rabbitmq
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbitmq-data/rabbitmq:/var/lib/rabbitmq
    networks:
      backend:
        ipv4_address: ${QUEUE_IP}

  web:
    image: lbanchio/docker-php-nginx:8.0-18.04
    container_name: web
    hostname: dev
    ports:
      - "8003:8003"
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx/sites-available
      - ${WEB_DIR}:/var/www
    environment:
      TZ: "America/Argentina/Cordoba"
      COMPOSER_CACHE_DIR: /var/www/.composer
      COMPOSER_HOME: /var/www/.composer
    depends_on:
      - rabbitmq
    networks:
      backend:
        ipv4_address: ${WEB_IP}

  mysql:
    image: mysql:8.0
    container_name: db
    hostname: mysql
    ports:
      - "3307:3307"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    depends_on:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      USER: 1000
    networks:
      backend:
        ipv4_address: ${DATABASE_IP}

  email:
    build: go
    container_name: email_app
    volumes:
      - ${EMAIL_APP_DIR}:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    restart: always
    depends_on:
      - web
    networks:
      backend:
        ipv4_address: ${EMAIL_APP_IP}


